# Generated by Django 4.0.5 on 2022-06-04 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.CreateModel(
            name='Gram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(max_length=2000)),
                ('photo', models.FileField(upload_to='grams/%y/')),
                ('posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gram.profile')),
            ],
        ),
    ]
