# Generated by Django 4.0.5 on 2022-06-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_profile_updated_gram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
